### ISSUE TITLE
Linux Binary Please

### ISSUE THREAD

**Issue by fenimore** [benjeee/ZoneLord#1]
:pray: :flushed:

**Comment by benjeee** [comment]
hey! sorry i missed this, I'd rather not keep binaries in the repo but once I iron out a few issues i'll throw some links in the readme

**Comment by fenimore** [comment]
OK 😳 😄

**Comment by fenimore** [comment]
hey any links yet, or releases? https://github.com/benjeee/ZoneLord/releases
